spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mapping: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false



  jackson:
    serialization:
      fail-on-empty-beans: false



server:
  port: 8030
  servlet:
    context-path:





